# -*- coding: utf-8 -*-
"""titanic_naive bayes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0z0VfNtW-RX3LocG2iJqnsl6QssGuA0
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

dataset= pd.read_csv('titanicsurvival.csv')

print(dataset.head(7))

survival_set=set(dataset['Sex'])
dataset['Sex']=dataset['Sex'].map({"female":0,"male":1}).astype(int)
print(dataset.head)

X = dataset.drop('Survived',axis='columns')

Y = dataset.Survived

X.columns[X.isna().any()]
X.Age = X.Age.fillna(X.Age.mean())
print(dataset.head(10))

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=0)



from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

pclassno = int(input("Enter person pclass number:"))
sex = int(input("Enter sex:"))
age = int(input("Enter Age:"))
Fare = float(input("Enter Fare:"))
person = [[pclassno,sex,age,Fare]]
result = model.predict(person)
print(result)
if result == 1:
  print("person Alive")
else:
    print("not Alive")

y_pred = model.predict(X_test)
print(np.column_stack((y_pred,y_test)))

from sklearn.metrics import accuracy_score
print('accuracy of the model:{0}%'.format(accuracy_score(y_test,y_pred)*100))